import os

import dotenv

dotenv.load_dotenv()

OLLAMA_URL = os.getenv("OLLAMA_URL")
AZURE_AI_APIKEY = os.getenv("AZURE_AI_APIKEY")
AZURE_AI_ENDPOINT = os.getenv("AZURE_AI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
LLAMAINDEX_APIKEY = os.getenv("LLAMAINDEX_APIKEY")